### ISSUE TITLE
Yamldiff Sequence items

### ISSUE THREAD

**Issue by stephengroat** [wallace/yamldiff#14]
Could you explain why I'm getting a `YamldiffKeyValueError` for these two yaml files? Is it because they use sequence items?

backup.yml
````
websites:
  - name: AeroFS
    url: https://www.aerofs.com/
    tfa: Yes
    software: Yes
    img: aerofs.png
    doc: https://www.aerofs.com/blog/two-factor-authentication-for-hybrid-and-private-cloud-md/
````
backup2.yml
````
websites:
  - name: AeroFS
    url: https://www.aerofs.com/
    tfa: Yes
    hardware: Yes
    software: Yes
    img: aerofs.png
    doc: https://www.aerofs.com/blog/two-factor-authentication-for-hybrid-and-private-cloud-md/
````

````
irb(main):002:0> result = Yamldiff.diff_yaml('_data/backup.yml','_data/backup2.yml')
=> {"_data/backup2.yml"=>[#<YamldiffKeyValueError:0x007fb4d7a50b20 @key="websites", @context=[], @diff=#<Diffy::Diff:0x007fb4d7a50cb0 @options={:diff=>"-U 10000", :source=>"strings", :include_diff_info=>false, :include_plus_and_minus_in_html=>false, :context=>nil, :allow_empty_diff=>true}, @string1="[{\"name\"=>\"AeroFS\", \"url\"=>\"https://www.aerofs.com/\", \"tfa\"=>true, \"software\"=>true, \"img\"=>\"aerofs.png\", \"doc\"=>\"https://www.aerofs.com/blog/two-factor-authentication-for-hybrid-and-private-cloud-md/\"}]\n", @string2="[{\"name\"=>\"AeroFS\", \"url\"=>\"https://www.aerofs.com/\", \"tfa\"=>true, \"hardware\"=>true, \"software\"=>true, \"img\"=>\"aerofs.png\", \"doc\"=>\"https://www.aerofs.com/blog/two-factor-authentication-for-hybrid-and-private-cloud-md/\"}]\n">>]}
````
